export const GET_POST_PENDING = "GET_POST_PENDING"
export const GET_POST_FULFILLED = "GET_POST_FULFILLED"
export const GET_POST_REJECTED = "GET_POST_REJECTED"



export const ADD_POST_PENDING = "ADD_POST_PENDING"
export const ADD_POST_FULFILLED = "ADD_POST_FULFILLED"
export const ADD_POST_REJECTED = "ADD_POST_REJECTED"


export const DELETE_POST_PENDING = "DELETE_POST_PENDING"
export const DELETE_POST_FULFILLED = "DELETE_POST_FULFILLED"
export const DELETE_POST_REJECTED = "DELETE_POST_REJECTED"

export const UPDATE_POST_PENDING = "UPDATE_POST_PENDING"
export const UPDATE_POST_FULFILLED = "UPDATE_POST_FULFILLED"
export const UPDATE_POST_REJECTED = "UPDATE_POST_REJECTED"

